package controller;

public enum Actions {
	CREATE_PRODUCT, ADD_PRODUCT, EDIT_PRODUCT, DELETE_PRODUCT, CHANGE_VIEW_PAGE, FILTER, VIEW_DETAILS, ADD_TO_SHOPPING, DISPLAY_CATEGORY_PRODUCTS, CANCEL, ACCEPT_ADD, GO_HOME_PAGE, LOG_IN_ADMIN, GET_QUERIES_GRAPHICS, GET_FULL_LIST_OF_PRODUCTS, ENTER_ADMIN_MODE, ENTER_USER_MODE, ADD_TO_SHOPPING_CAR, CLOSE_ADMIN_SESSION;
}
